### PR TITLE
fix issue #12 #13 #14 #16

### PR DESCRIPTION
**Pull request by MahmoudMabrok**
for #20 
-filter repos based on language

for #19 
- number of  gists 
- location
- number of of followers
- number of of following
- when join github

for #16 
- add  more details (project size, language, stars count, count of forks).
- distinguish between forked and non-forked repos

for #14 
- add screen/layout to load user repos.

for #13  
- show error when user enter empty user name.
- show error when not found user at github.
- show error when no network is exist.
- add loading indicator while loading.

for #12  
- add table-like layout to display user info

### CODE REVIEW

**Comment by atm1504** [comment]
Please attach a gif to show the app in action

**Comment by MahmoudMabrok** [comment]
@atm1504  this is : https://drive.google.com/open?id=16RTgLJO17i-iSW--DRW-Lw-7__hTo58g

**Comment by atm1504** [comment]
Please squash all the commits, it will help us to review! Thank u : )

**Comment by MahmoudMabrok** [comment]
i have no experience with squashing (as i search it may cause problems)

**Comment by MahmoudMabrok** [comment]
@atm1504  did i squashed them correctly?

**Comment by MahmoudMabrok** [comment]
@Bhavnaharitsa review PR

**Comment by Bhavnaharitsa** [comment]
No squashing is not dome properly

**Comment by atm1504** [comment]
Resolve the conflict

**Comment by MahmoudMabrok** [comment]
@atm1504  i solved conflict

**Comment by MahmoudMabrok** [comment]
is that enough for reviewing [link](https://github.com/NJACKWinterOfCode/Github_Profile_APP/pull/15/commits/45b38dac1a43bad140830271457df6be33a5f28e)

**Comment by MahmoudMabrok** [comment]
> No squashing is not dome properly
@atm1504  @Bhavnaharitsa 
i squashed them but choose squash not fix as option so message still exists. 
 
Screenshot from 2020-01-04 09-34-54

as i am beginner with work with forking so i made a PR and push commits with same branch but next time i will create a branch for each new feature so that it becomes a separate PR.

**Comment by atm1504** [comment]
@MahmoudMabrok okk.
Please resolve the conflict and get it merged.

**Comment by MahmoudMabrok** [comment]
review before period ends @atm1504  

or should i delete all and fork then make pr again but u should be fast to review it

**Comment by atm1504** [comment]
> review before period ends @atm1504
> or should i delete all and fork then make pr again but u should be fast to review it

Don't worry you will still get points if the period ends as your pr has been created before the end of the period

**Review by atm1504 — APPROVED** [review]
LGTM

**Comment by MahmoudMabrok** [comment]
#17 was included here I am sorry @atm1504

**Pull request merged**
